---
title: "Arbeit mit Tabellen"
output:
  learnr::tutorial:
    language: de
    css: css/boxes.css
    fig_caption: yes
    df_print: default
runtime: shiny_prerendered
bibliography: ref.json
link-citations: TRUE
description: Was sind Data Frames? Das Indizieren mit $-Operator wird geübt. 
resource_files:
- css/boxes.css
editor_options:
  markdown:
    canonical: true
---

```{r setup, include=FALSE}
library(learnr)
library(tidyverse)
library(nycflights13)
knitr::opts_chunk$set(echo = TRUE)
```

## Data Frames {data-progressive="TRUE"}

### Einführung

Dieses Kapitel zeigt dir die Objektklasse, mit welcher du hauptsächlich arbeiten wirst. Ein *Data Frame* ist die Struktur, mit der **Tabellen** in R repräsentiert werden.

Wenn du mit Tabellen in R zu tun haben wirst - und das wird oft sein - wird es sich meist um *Data Frames* oder eine spezielle Unterform davon, *Tibbles*, handeln. Beides wirst du in diesem Tutorial kennenlernen.

Dass Du den Umgang mit Tabellen in R lernst, ist essentiell, da die meisten Daten auf dieser Welt irgendwie in Tabellen dargestellt werden.

Im Tutorial "Vektoren" hast du gelernt, dass Vektoren Variablen darstellen und mehrere Werte enthalten können.

In nächsten Abschnitt lernst du, wie du mehrere Vektoren in einer Tabelle zusammenbringen kannst.

::: blau-nb
Übrigens: Wir verwenden hier für die Eindeutschung "der" Data Frame, die innerliche Begründung lautet: *Frame* = Rahmen, "der" Rahmen :)
:::

### Listen

Willkommen zum Tutorial über Listen und Data Frames! Hier lernst du, wie du Daten in R strukturierter organisieren kannst. Fangen wir mit Listen an.

\<\<<Erklärung anfügen>\>\>

### Listen erstellen

Eine Liste ist eine flexible Datenstruktur, die es dir ermöglicht, verschiedene Datentypen zu speichern. Hier ist ein Beispiel:

\<\<<Beispiel anfügen>\>\>

\<\<<Aufgabe anfügen>\>\>

### Data Frames

Eine besondere Art von Liste ist der Data Frame. Ein Data Frame organisiert Daten in tabellarischer Form.

\<\<<Erklärung anfügen>\>\>

\<\<<Beispiel anfügen>\>\>

\<\<<Aufgabe anfügen>\>\>

#### Data Frame Subsetting

\<\<<Erklärung anfügen>\>\>

##### Matrix Subsetting

##### List Subsetting

##### Data Frame verändern

Manchmal möchtest du Spalten oder Zeilen hinzufügen oder entfernen.

\<\<<Erklärung anfügen>\>\>

\<\<<Beispiel anfügen>\>\>

::: aufgabe
Füge dem Data Frame wg_df eine neue Spalte namens miete hinzu, indem du den grundpreis mit der quadratmeter multiplizierst. Entferne die Spalte balkon aus dem Data Frame wg_df.
:::

## Credit

<!-- vielleicht in diese Richtung? -->

Dieses Tutorial wurde (größtenteils) von Lukas Bruelheide sowie in Teilen von Marie Klosterkamp geschrieben.

ggf.: Bei der Erstellung (u.a. der Beispiele, Aufgaben und Zusammenfassung) wurde teilweise von ChatGPT gebrauch gemacht.
